name: petani_maju
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  connectivity_plus: ^6.1.0
  geolocator: ^14.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  supabase_flutter: ^2.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.4.1

  table_calendar: ^3.1.2
  workmanager: ^0.9.0+3
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  easy_localization: ^3.0.8
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - .env
